/**
 * OnboardingOrchestrator — submits catalog-info.yaml PRs for one or many repos.
 *
 * Wraps CatalogImportApi.submitPullRequest and maps HTTP/network errors to
 * typed outcome variants so callers don't need to inspect raw error codes.
 *
 * CatalogImportApi is intentionally a minimal subset of the real
 * @backstage/plugin-catalog-import CatalogImportApi — it only requires
 * submitPullRequest, which is the only method OnboardingOrchestrator uses.
 * The real API (a structural superset) satisfies this interface.
 */
export interface CatalogImportApi {
  submitPullRequest(options: {
    repositoryUrl: string;
    fileContent: string;
    title: string;
    body: string;
  }): Promise<{ link: string; location: string }>;
}

/** A single-repo request in a bulk onboarding job. */
export type BulkRequest = { owner: string; repo: string; yaml: string };

/** Progress event emitted by onboardBulk for each repo processed. */
export type BulkProgressEvent =
  | { type: 'started'; repo: string; owner: string }
  | { type: 'finished'; repo: string; owner: string; result: OnboardResult };

/** Typed outcome of a single-repo onboarding attempt. */
export type OnboardResult =
  | { kind: 'success'; prUrl: string }
  | { kind: 'skipped'; reason: 'pr-exists'; prNumber?: number; prUrl?: string }
  | { kind: 'failed-retry'; reason: string; nextAttemptAt?: Date }
  | { kind: 'failed-perm'; reason: string };

export const DEFAULT_PR_TITLE = 'chore: register in Backstage catalog';

export const DEFAULT_PR_BODY = `This PR adds a \`catalog-info.yaml\` file to register this repository in the Backstage software catalog.

The file was auto-generated by Backstage based on repository metadata. You can edit the file before merging.

📖 [catalog-info.yaml field reference](https://backstage.io/docs/features/software-catalog/descriptor-format)`;

/** Extracts a numeric HTTP status from an unknown error, or returns undefined. */
const extractStatus = (err: unknown): number | undefined => {
  if (err && typeof err === 'object') {
    const e = err as Record<string, unknown>;
    if (typeof e.statusCode === 'number') return e.statusCode;
    if (typeof e.status === 'number') return e.status;
    if (typeof e.response === 'object' && e.response !== null) {
      const r = e.response as Record<string, unknown>;
      if (typeof r.status === 'number') return r.status;
    }
  }
  return undefined;
};

/** Best-effort human-readable message for an unknown thrown value. */
const errorMessage = (err: unknown): string => {
  if (err instanceof Error) return err.message;
  if (typeof err === 'string') return err;
  return 'Unknown error';
};

/** Returns true if err is a ConflictError (name or statusCode 409). */
const isConflictError = (err: unknown): boolean => {
  if (err && typeof err === 'object') {
    const e = err as Record<string, unknown>;
    if (e.name === 'ConflictError') return true;
    if (extractStatus(e) === 409) return true;
  }
  return false;
};

/** Returns true if err is a network timeout / AbortError. */
const isAbortError = (err: unknown): boolean => {
  if (err && typeof err === 'object') {
    const e = err as Record<string, unknown>;
    return e.name === 'AbortError';
  }
  return false;
};

/**
 * Attempts to extract an existing PR URL from a conflict error body.
 * Returns undefined if no URL can be found.
 */
const extractPrUrlFromError = (err: unknown): string | undefined => {
  if (!err || typeof err !== 'object') return undefined;
  const e = err as Record<string, unknown>;
  if (typeof e.message === 'string') {
    const match = e.message.match(/https:\/\/github\.com\/[^\s"]+\/pull\/\d+/);
    if (match) return match[0];
  }
  return undefined;
};

/**
 * Orchestrates single-repo onboarding: creates a PR with the supplied YAML via
 * CatalogImportApi and returns a typed result.
 */
export class OnboardingOrchestrator {
  constructor(private readonly catalogImportApi: CatalogImportApi) {}

  /**
   * Submit a pull request to add catalog-info.yaml to a GitHub repository.
   *
   * @param owner - GitHub org or user name.
   * @param repo  - Repository name.
   * @param suggestionYaml - Content of the catalog-info.yaml to commit.
   * @param title - PR title (defaults to a standard chore message).
   * @param body  - PR body (defaults to a standard description).
   */
  async onboardSingle(
    owner: string,
    repo: string,
    suggestionYaml: string,
    title?: string,
    body?: string,
  ): Promise<OnboardResult> {
    const repositoryUrl = `https://github.com/${owner}/${repo}`;
    try {
      const result = await this.catalogImportApi.submitPullRequest({
        repositoryUrl,
        fileContent: suggestionYaml,
        title: title ?? DEFAULT_PR_TITLE,
        body: body ?? DEFAULT_PR_BODY,
      });
      return { kind: 'success', prUrl: result.link };
    } catch (err: unknown) {
      return this.mapError(err);
    }
  }

  /**
   * Process multiple repos sequentially, emitting progress events for each one.
   *
   * Yields a `started` event before each repo and a `finished` event after it
   * completes. Checks the abort signal before each repo; stops cleanly if aborted.
   *
   * @param repos  - List of repos to onboard with their pre-fetched YAML.
   * @param signal - Optional AbortSignal to stop processing early.
   */
  async *onboardBulk(
    repos: Array<BulkRequest>,
    signal?: AbortSignal,
  ): AsyncIterable<BulkProgressEvent> {
    for (const { owner, repo, yaml } of repos) {
      if (signal?.aborted) break;
      yield { type: 'started', repo, owner };
      const result = await this.onboardSingle(owner, repo, yaml);
      yield { type: 'finished', repo, owner, result };
    }
  }

  private mapError(err: unknown): OnboardResult {
    if (isConflictError(err)) {
      return {
        kind: 'skipped',
        reason: 'pr-exists',
        prUrl: extractPrUrlFromError(err),
      };
    }

    const status = extractStatus(err);

    if (status === 422) {
      return {
        kind: 'skipped',
        reason: 'pr-exists',
        prUrl: extractPrUrlFromError(err),
      };
    }

    if (status === 429 || isAbortError(err)) {
      if (isAbortError(err)) {
        return { kind: 'failed-retry', reason: 'Network timeout' };
      }
      return {
        kind: 'failed-retry',
        reason: 'Rate limited by GitHub',
        nextAttemptAt: new Date(Date.now() + 60_000),
      };
    }

    const message = errorMessage(err);

    // 403 is both a GitHub scope problem and what the backend's owner allowlist
    // returns (ADR 019). The server's message says which, so keep it and name
    // both remediations rather than asserting one cause.
    if (status === 403) {
      return {
        kind: 'failed-perm',
        reason: `${message}. Check catalogCoverage.allowedOwners and the GitHub token's 'repo' scope.`,
      };
    }

    return { kind: 'failed-perm', reason: message };
  }
}
