import { Request, Response } from 'express';
import {
  GITHUB_API,
  makeGithubHeaders,
  readGithubJson,
} from './githubClient';
import { SchemaValidator } from '../services/SchemaValidator';

const BRANCH = 'backstage-integration';
const FILE_PATH = 'catalog-info.yaml';
const FALLBACK_TITLE = 'chore: register in Backstage catalog';
const FALLBACK_BODY =
  'This PR adds a `catalog-info.yaml` file to register this repository in the Backstage software catalog.\n\n' +
  'The file was auto-generated by Backstage based on repository metadata. You can edit the file before merging.\n\n' +
  '📖 [catalog-info.yaml field reference](https://backstage.io/docs/features/software-catalog/descriptor-format)';

export type OnboardHandlerOptions = {
  prTitle?: string;
  prBody?: string;
  /** GitHub token resolved from config/env by the router. */
  token?: string;
  /** Validates the submitted YAML against the Backstage entity schema. */
  validator?: SchemaValidator;
};

/**
 * Returns a POST /repos/:owner/:repo/onboard handler.
 * Defaults for PR title and body can be overridden via app-config (catalogCoverage.pr.*).
 * The request body may still override both via `title` and `body` fields.
 */
export const createOnboardHandler =
  (defaults: OnboardHandlerOptions = {}) =>
  async (req: Request, res: Response): Promise<void> => {
    const { owner, repo } = req.params;
    const {
      yaml: fileContent,
      title: prTitle,
      body: prBody,
    } = req.body as {
      yaml?: string;
      title?: string;
      body?: string;
    };

    if (!fileContent) {
      res.status(400).json({ error: 'yaml is required' });
      return;
    }

    const validation = defaults.validator?.validate(fileContent);
    if (validation && !validation.valid) {
      res.status(400).json({
        error: 'Submitted YAML is not a valid Backstage entity',
        details: validation.errors,
      });
      return;
    }

    const token = defaults.token;
    if (!token) {
      res
        .status(500)
        .json({ error: 'GITHUB_TOKEN not configured on the server' });
      return;
    }

    const h = makeGithubHeaders(token);
    const commitTitle = prTitle ?? defaults.prTitle ?? FALLBACK_TITLE;
    const commitBody = prBody ?? defaults.prBody ?? FALLBACK_BODY;

    // 1. Get default branch
    const repoInfoRes = await fetch(`${GITHUB_API}/repos/${owner}/${repo}`, {
      headers: h,
    });
    const repoInfo = await readGithubJson<{ default_branch: string }>(
      res,
      repoInfoRes,
      'Failed to fetch repo info',
    );
    if (!repoInfo) return;
    const { default_branch: defaultBranch } = repoInfo;

    // 2. Get HEAD SHA of the default branch
    const refRes = await fetch(
      `${GITHUB_API}/repos/${owner}/${repo}/git/ref/heads/${defaultBranch}`,
      { headers: h },
    );
    const ref = await readGithubJson<{ object: { sha: string } }>(
      res,
      refRes,
      'Failed to fetch branch ref',
    );
    if (!ref) return;
    const baseSha = ref.object.sha;

    // 3. Create backstage-integration branch (422 = already exists)
    const branchRes = await fetch(
      `${GITHUB_API}/repos/${owner}/${repo}/git/refs`,
      {
        method: 'POST',
        headers: h,
        body: JSON.stringify({ ref: `refs/heads/${BRANCH}`, sha: baseSha }),
      },
    );
    if (branchRes.status !== 422) {
      const branch = await readGithubJson(
        res,
        branchRes,
        'Failed to create branch',
      );
      if (!branch) return;
    }

    // 4. Check if catalog-info.yaml exists on the branch (for update SHA)
    let existingFileSha: string | undefined;
    const existingRes = await fetch(
      `${GITHUB_API}/repos/${owner}/${repo}/contents/${FILE_PATH}?ref=${BRANCH}`,
      { headers: h },
    );
    if (existingRes.ok) {
      existingFileSha = ((await existingRes.json()) as { sha: string }).sha;
    }

    // 5. Create or update catalog-info.yaml
    const filePayload: Record<string, string> = {
      message: 'chore: add catalog-info.yaml',
      content: Buffer.from(fileContent).toString('base64'),
      branch: BRANCH,
    };
    if (existingFileSha) filePayload.sha = existingFileSha;

    const fileRes = await fetch(
      `${GITHUB_API}/repos/${owner}/${repo}/contents/${FILE_PATH}`,
      { method: 'PUT', headers: h, body: JSON.stringify(filePayload) },
    );
    const file = await readGithubJson(res, fileRes, 'Failed to commit file');
    if (!file) return;

    // 6. Open PR (422 = already exists)
    const prRes = await fetch(`${GITHUB_API}/repos/${owner}/${repo}/pulls`, {
      method: 'POST',
      headers: h,
      body: JSON.stringify({
        title: commitTitle,
        body: commitBody,
        head: BRANCH,
        base: defaultBranch,
      }),
    });

    if (prRes.status === 422) {
      const openPrsRes = await fetch(
        `${GITHUB_API}/repos/${owner}/${repo}/pulls?head=${owner}:${BRANCH}&state=open`,
        { headers: h },
      );
      if (openPrsRes.ok) {
        const openPrs = (await openPrsRes.json()) as Array<{
          html_url: string;
        }>;
        if (openPrs.length > 0) {
          res.status(409).json({
            error: 'A pull request already exists',
            prUrl: openPrs[0].html_url,
          });
          return;
        }
      }
      res.status(409).json({ error: 'Pull request already exists' });
      return;
    }

    const pr = await readGithubJson<{ html_url: string }>(
      res,
      prRes,
      'Failed to open pull request',
    );
    if (!pr) return;

    const { html_url: prUrl } = pr;
    res.json({
      link: prUrl,
      location: `https://github.com/${owner}/${repo}/blob/${BRANCH}/${FILE_PATH}`,
    });
  };
